"""Initial migration1.

Revision ID: 321c501611d8
Revises: 
Create Date: 2022-01-14 23:10:46.804911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321c501611d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'cust_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('cust_email', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
